title: SQL DevOps workshop
description: SQL projects and source control integration for SQL in Fabric, Azure SQL, and SQL Server

# jeklyl base settings
theme: minima
url: ""
baseurl: ""

# theme settings
perma_link: "https://aka.ms/sql-devops-workshop"
github_repo: "dzsquared/sql-devops-workshop"

header_pages:
  - LAB1/README.md
  - LAB2/README.md
  - LAB3/README.md
  - LAB4/README.md
